image: debian:jessie 
before_script:
  - apt-get update -qq
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -n "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

stages:
  - test
  - deploy
 
Test on Staging:
  type: test
  environment: staging
  script:
    - ssh root@162.220.165.19 "bash -ac 'cd /home/videopath/api && git fetch origin && git reset --hard origin/develop && source /home/videopath/envs/api/bin/activate && ./app.sh test'"
    
Deploy to Staging:
  type: deploy
  script:
    - ssh root@162.220.165.19 "cd /home/videopath/; ./scripts/deploy-api-staging.sh "
  environment: staging
  only:
    - develop
    
Deploy to Production:
  type: deploy
  script:
    - heroku pg:backups capture --app videopath-api
    - dpl --provider=heroku --app=videopath-api --api-key=$HEROKU_API_KEY
    - heroku run python manage.py migrate --noinput --exit-code --app videopath-api
  environment: production
  only:
    - master
  when: manual
